#!/bin/bash -l
#SBATCH --job-name="run_nbody"
#SBATCH --account="uzh8"
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=36
#SBATCH --partition=debug
#SBATCH --constraint=mc
#SBATCH --hint=nomultithread
#SBATCH --output="nbody_for2.log"
#SCATCH --error="nbody_for2.error"

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun nbody_for2
